# Generated by Django 5.1 on 2024-09-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='stock',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizer_shop.fertilizer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(to='fertilizer_shop.cartitem')),
            ],
        ),
    ]
