# Generated by Django 5.1 on 2024-09-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizer_shop', '0002_fertilizer_stock_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='image',
            field=models.ImageField(upload_to='fertilizers/'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
